[[ArnoldiMethod]]
deps = ["DelimitedFiles", "LinearAlgebra", "Pkg", "Random", "SparseArrays", "StaticArrays", "Test"]
git-tree-sha1 = "2b6845cea546604fb4dca4e31414a6a59d39ddcd"
uuid = "ec485272-7323-5ecc-a04f-4719b315124d"
version = "0.0.4"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[BinaryProvider]]
deps = ["Libdl", "Pkg", "SHA", "Test"]
git-tree-sha1 = "38be61810f280c3c478f5c38aaf387f8f9199275"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.1"

[[Calculus]]
deps = ["Compat"]
git-tree-sha1 = "f60954495a7afcee4136f78d1d60350abd37a409"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.4.1"

[[Clustering]]
deps = ["Dates", "Distances", "LinearAlgebra", "NearestNeighbors", "Pkg", "Printf", "Random", "SparseArrays", "Statistics", "StatsBase", "Test"]
git-tree-sha1 = "282e5d488cfca89b78b28b9ef28a59898951a62f"
uuid = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
version = "0.12.1"

[[CodecZlib]]
deps = ["BinaryProvider", "Libdl", "Pkg", "Test", "TranscodingStreams"]
git-tree-sha1 = "83cb3d65c37ea1364c2d5bf7bcea41843ba645dc"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.5.0"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random", "Test"]
git-tree-sha1 = "f73b0e10f2a5756de7019818a41654686da06b09"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.5"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Pkg", "Printf", "Reexport", "Test"]
git-tree-sha1 = "8c89e0a9a583954eae3efcf6a531e51c02b38cee"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.4"

[[CommonSubexpressions]]
deps = ["Test"]
git-tree-sha1 = "efdaf19ab11c7889334ca247ff4c9f7c322817b0"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.2.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "ff2595695fc4f14427358ce2593f867085c45dcb"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.2.0"

[[Conda]]
deps = ["Compat", "JSON", "VersionParsing"]
git-tree-sha1 = "85b5bf3ffcf4f39abe019dab1dd00a0aead8d882"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.0.2"

[[Contour]]
deps = ["LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "b974e164358fea753ef853ce7bad97afec15bb80"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.5.1"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "8fc6e166e24fda04b2b648d4260cdad241788c54"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.14.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffEqDiffTools]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "9c7a902a53542b5b3178a2ed16878bda02685456"
uuid = "01453d9d-ee7c-5054-8395-0335cb756afa"
version = "0.6.0"

[[DiffResults]]
deps = ["Compat", "StaticArrays"]
git-tree-sha1 = "db8acf46717b13d6c48deb7a12007c7f85a70cf7"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "0.0.3"

[[DiffRules]]
deps = ["Random", "Test"]
git-tree-sha1 = "c49ec69428ffea0c1d1bbdc63d1a70f5df5860ad"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "0.0.7"

[[Distances]]
deps = ["LinearAlgebra", "Pkg", "Printf", "Random", "Statistics", "Test"]
git-tree-sha1 = "2f38605722542f1c0a32dd2856fb529d8c226c69"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.7.3"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[FillArrays]]
deps = ["Compat", "LinearAlgebra", "Random", "SparseArrays"]
git-tree-sha1 = "c80c54ba3341ffc3c64e817f742ce77564ad410c"
uuid = "1a297f60-69ca-5386-bcde-b61e274b549b"
version = "0.2.1"

[[FixedPointNumbers]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "b8045033701c3b10bf2324d7203404be7aef88ba"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.3"

[[ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "InteractiveUtils", "LinearAlgebra", "NaNMath", "Pkg", "Random", "SparseArrays", "SpecialFunctions", "StaticArrays", "Test"]
git-tree-sha1 = "8425a7d4e060bc2ded32d090bce910a187d6cce7"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.9.0"

[[GR]]
deps = ["Base64", "DelimitedFiles", "Pkg", "Random", "Serialization", "Sockets", "Test"]
git-tree-sha1 = "0437921cbf8ee555ab7a2a3115c1d0907289e816"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.34.1"

[[IJulia]]
deps = ["Base64", "Compat", "Conda", "Dates", "InteractiveUtils", "JSON", "Markdown", "MbedTLS", "Pkg", "Printf", "REPL", "Random", "SoftGlobalScope", "Test", "UUIDs", "ZMQ"]
git-tree-sha1 = "a4696d3b0153be227669db080e2c36ebce59ed88"
uuid = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
version = "1.12.0"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Pkg", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "fec8e4d433072731466d37ed0061b3ba7f70eeb9"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.19.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LightGraphs]]
deps = ["ArnoldiMethod", "Base64", "CodecZlib", "DataStructures", "DelimitedFiles", "Distributed", "LinearAlgebra", "Markdown", "Pkg", "Random", "SharedArrays", "SimpleTraits", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "446a9cf208ec401ae67e517de4eeceaf2cd5cdac"
uuid = "093fc24a-ae57-5d10-9952-331d41423f4d"
version = "1.1.0"

[[LineSearches]]
deps = ["LinearAlgebra", "NLSolversBase", "NaNMath", "Parameters", "Printf", "Test"]
git-tree-sha1 = "31d89c1b2594d741cb78f5fc7cb616762a71b559"
uuid = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
version = "7.0.0"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "c443e1c8d58a4e9f61b708ad0a88286c7042145b"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.4"

[[MappedArrays]]
deps = ["Test"]
git-tree-sha1 = "923441c5ac942b60bd3a842d5377d96646bcbf46"
uuid = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
version = "0.2.1"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MbedTLS]]
deps = ["BinaryProvider", "Libdl", "Pkg", "Random", "Sockets", "Test"]
git-tree-sha1 = "3775d205b09b624aa06d39012a8920ba99cb3b8b"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "0.6.3"

[[Measures]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "ddfd6d13e330beacdde2c80de27c1c671945e7d9"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.3.0"

[[Missings]]
deps = ["Dates", "InteractiveUtils", "SparseArrays", "Test"]
git-tree-sha1 = "adc26d2ee85a49c413464110d922cf21efc9d233"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.3.1"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NLSolversBase]]
deps = ["Calculus", "DiffEqDiffTools", "DiffResults", "Distributed", "ForwardDiff", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "75f08d4dd9174855aefe4dc9532569450bffcd93"
uuid = "d41bc354-129a-5804-8e4c-c37616107c6c"
version = "7.1.0"

[[NaNMath]]
deps = ["Compat"]
git-tree-sha1 = "ce3b85e484a5d4c71dd5316215069311135fa9f2"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.2"

[[NearestNeighbors]]
deps = ["Distances", "LinearAlgebra", "Mmap", "Pkg", "StaticArrays", "Test"]
git-tree-sha1 = "aab46b96ae5c2a9c08146188016d6312276094e5"
uuid = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
version = "0.4.2"

[[Optim]]
deps = ["Calculus", "Compat", "DiffEqDiffTools", "ForwardDiff", "LineSearches", "LinearAlgebra", "NLSolversBase", "NaNMath", "Parameters", "Pkg", "PositiveFactorizations", "Printf", "Random", "SparseArrays", "StatsBase", "Test"]
git-tree-sha1 = "0ed8809e72d3b595930c8ade539838a99f94dc8b"
uuid = "429524aa-4258-5aef-a3af-852621145aeb"
version = "0.16.0"

[[OrderedCollections]]
deps = ["Pkg", "Random", "Serialization", "Test"]
git-tree-sha1 = "85619a3f3e17bb4761fe1b1fd47f0e979f964d5b"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.0.2"

[[Parameters]]
deps = ["Markdown", "OrderedCollections", "Pkg", "REPL", "Test"]
git-tree-sha1 = "40f540ec96e50c0b2b9efdb11b5e4d0c63f90923"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.10.1"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[PlotThemes]]
deps = ["PlotUtils", "Requires", "Test"]
git-tree-sha1 = "f3afd2d58e1f6ac9be2cea46e4a9083ccc1d990b"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "0.3.0"

[[PlotUtils]]
deps = ["Colors", "Dates", "Printf", "Random", "Reexport", "Test"]
git-tree-sha1 = "78553a920c4869d20742ba66193e3692369086ec"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "0.5.4"

[[Plots]]
deps = ["Base64", "Contour", "Dates", "FixedPointNumbers", "GR", "JSON", "LinearAlgebra", "Measures", "NaNMath", "Pkg", "PlotThemes", "PlotUtils", "Printf", "REPL", "RecipesBase", "Reexport", "Requires", "Showoff", "SparseArrays", "StaticArrays", "Statistics", "StatsBase", "Test", "UUIDs"]
git-tree-sha1 = "935241178e80158451cc33f4af7c57f671b881b8"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "0.19.3"

[[PositiveFactorizations]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "86ae7329c4b5c266acf5c7c524a972300d991e1c"
uuid = "85a6dd25-e78a-55b7-8502-1745935b8125"
version = "0.2.1"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[ProgressMeter]]
deps = ["Printf", "Random", "Test"]
git-tree-sha1 = "09e653f4b0a3c44628f0bdd0a0e58bc92e0264ef"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "0.6.0"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RecipesBase]]
deps = ["Pkg", "Random", "Test"]
git-tree-sha1 = "b18c3d875ad6805e3db59c4e81f206f04df71d66"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.5.0"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[SNAPDatasets]]
deps = ["LightGraphs", "Pkg", "Test"]
git-tree-sha1 = "4df9b4298f93608554a6f3131fd7a1ce662734eb"
uuid = "fc66bc1b-447b-53fc-8f09-bc9cfb0b0c10"
version = "0.1.0"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Showoff]]
deps = ["Compat", "Pkg"]
git-tree-sha1 = "276b24f3ace98bec911be7ff2928d497dc759085"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "0.2.1"

[[SimpleTraits]]
deps = ["InteractiveUtils", "MacroTools", "Pkg", "Test"]
git-tree-sha1 = "c0a542b8d5e369b179ccd296b2ca987f6da5da0a"
uuid = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
version = "0.8.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SoftGlobalScope]]
deps = ["Test"]
git-tree-sha1 = "97f6dfcf612b9a7260fde44170725d9ea34b1431"
uuid = "b85f4697-e234-5449-a836-ec8e2f98b302"
version = "1.0.7"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "03f5898c9959f8115e30bc7226ada7d0df554ddd"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.1"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Libdl", "Test"]
git-tree-sha1 = "c35c9c76008babf4d658060fc64aeb369a41e7bd"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.7.1"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d432c79bef174a830304f8601427a4357dfdbfb7"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "723193a13e8078cec6dcd0b8fe245c8bfd81690e"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.25.0"

[[TSne]]
deps = ["Distances", "LinearAlgebra", "Pkg", "Printf", "ProgressMeter", "Random", "Statistics", "Test"]
git-tree-sha1 = "4a1721f9c0e4dae699c3394bfc60bf88e04f39a6"
uuid = "24678dba-d5e9-5843-a4c6-250288b04835"
version = "1.2.0"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["DelimitedFiles", "Pkg", "Random", "Test"]
git-tree-sha1 = "a34a2d588e2d2825602bf14a24216d5c8b0921ec"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.8.1"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "c9d5aa108588b978bd859554660c8a5c4f2f7669"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.3"

[[ZMQ]]
deps = ["BinaryProvider", "FileWatching", "Libdl", "Sockets", "Test"]
git-tree-sha1 = "34e7ac2d1d59d19d0e86bde99f1f02262bfa1613"
uuid = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
version = "1.0.0"
